### ISSUE TITLE
Duplicate entries in the strings file

### ISSUE THREAD

**Issue by samreid** [phetsims/build-an-atom#108]
Discovered during #107, tagging @jbphet

**Comment by jbphet** [comment]
Probably a result of some recent revisions I made to the strings.  I'll fix.

**Comment by jbphet** [comment]
I believe that this is now fixed in all BAA string files.  They key ```symbol``` was only duplicated in the English file, not sure how this occurred, but it is now gone.  Two of the other strings ended up as duplicates when their names were simplified, so the duplicates were removed and they are now essentially consolidated into a single entry.  The string with the key ```whatIsTheTotalCharge``` ended up with duplicates when the key was simplified, but there truly is a need for two strings, a single-line version and a multi-line version, so the key for the multi-line version was revised to be ```whatIsTheTotalChargeMultiLine```.

Assigning back to @samreid.  However this was detected before, please see if it appears to be fully resolved.

**Comment by samreid** [comment]
IDEA no longer reports duplicate keys in the BAA strings file, closing.
