### ISSUE TITLE
Nav Bar Symbol Icon is incorrect

### ISSUE THREAD

**Issue by aadish** [phetsims/build-an-atom#114]
On the Nav Bar Symbol Icon shows Hydrogen with 2 protons which is incorrect

**Comment by jbphet** [comment]
It appears that some fixes that were made on the 1.1 branch for the symbol were never propagated to the master branch.  I couldn't just cherry-pick the commit from the 1.1 branch because the artwork asset files have been converted from SVG to Adobe Illustrator since the 1.1 release, so I manually imported the old SVG files, saved them as AI files, and re-exported the errant icon.  Should be taken care of now, closing.
