### ISSUE TITLE
Multiple instances of the "Electron Cloud" view property

### ISSUE THREAD

**Issue by phet-steele** [phetsims/build-an-atom#144]
Why are there two of these? (four if you count the symbol screen)

<img width="602" alt="screen shot 2017-03-03 at 10 42 26 am" src="https://cloud.githubusercontent.com/assets/5863899/23562088/46fcd4ce-fffe-11e6-8baf-c6470acce715.png">

They both do the same thing: set the visibility of the electron cloud. We could probably get by with only one? The top instance is toggled in conjunction with changing between the "Orbits" and "Cloud" radio button, but the bottom can only be changed manually. What I mean by that:

Watch the visibility of the orange highlighted text. It toggles when I switch between radio button selections in the sim. The yellow highlighted text's visibility does not change:
![baaio01](https://cloud.githubusercontent.com/assets/5863899/23562360/58d7aad8-ffff-11e6-8279-385f50d649df.gif)

Seen on macOS 10.12.3 Chrome. For phetsims/tasks/issues/792.

**Comment by jbphet** [comment]
The problem existed because the `ElectronCloudView` type was a scenery node that contained a circle node that was also called `electronCloudNode` in the tandem namespace.  I could have simply renamed the circle node, but decided instead to simplify the code a bit and make `ElectronCloudView` descend directly from `Circle`.  I've tested it myself and it seems to work fine, and it resolves the problem pointed out by this GitHub issue.  I'll unassign for now and will list this with the issues to be verified during the next RC.

**Comment by phet-steele** [comment]
This works much better @jbphet, thanks!
