### ISSUE TITLE
User reported issue: +/- Ion symbol ordering.

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/build-an-atom#180]
> In IUPAC 2005 http://old.iupac.org/publications/books/rbook/Red_Book_2005.pdf
> 
> IR-3.2 INDICATION OF MASS, CHARGE AND ATOMIC NMBER USING INDEXES (SUBSCRIPTS AND SUPERSCRITS)
> ...
> right upper index     charge
> A charge placed on an atom of symbol A is indicated as An+ or An-, not as A+n or A-n.
> 
> But in HTML5 sims it appears as +n

**Comment by oliver-phet** [comment]
We just received another request for customizing the order of the ion symbol from our German translators:
> As this sim is used to teach the difference between atoms and ions and ions are written as "Be2+" or "S2-", I find the representation in the sim slightly confusing for students ("Be+2"). It would be easier for them to link the proton and electron numbers from the sim with the ions they encounter in reactions if the representation of multiple charges were the same. For a single atom the charge can well be represented in the "2+" way, as it is common for ions.

**Comment by oliver-phet** [comment]
Assigning to @DianaTavares since she is the responsible designer!

**Comment by DianaTavares** [comment]
I ask Robert Parson about this, and this is his answer: 

_Having the number before the charge, e.g. Ca2+, is the usual convention in chemistry and **is probably what the sim should use.**  Note that chemists also commonly omit the numeral “1” when there is a single charge, but when the eim was designed the designers chose to keep it in order to make the notation as clear as possible for newcomers, and I would recommend continuing to do so._ 

I know that this simulation is also used for some math activities related to negative/positive integers numbers, then one option is to have both representation with a query parameter. Other way I think is better to use what is correct for a chemistry standpoint, an that mean the +/- to the right of the number. 

It is a super easy change in the sim, but I feel that this need a little of discussion, then I would like to know @ariel-phet , @arouinfar  and @amanda-phet (for the math side) opinion.

**Comment by jbphet** [comment]
To aid in the discussion, here are a couple of screenshots.  First is the notation recommended in the document:

![image](https://user-images.githubusercontent.com/3082831/195949315-0e7d3bf2-f0cd-4883-9a47-bd02e1afb9a9.png)

Here is how the sim currently depicts the same ionic charge:

![image](https://user-images.githubusercontent.com/3082831/195949482-5da8fde8-0a93-459c-9ea1-6721f6571022.png)

**Comment by amanda-phet** [comment]
The math activities that use this sim rely on the "net charge" feature on the first screen of this sim, so I'm not sure the changes being discussed here would impact those lessons. Thank you for taking them into consideration!

**Comment by arouinfar** [comment]
We are clearly not using the standard charge notation. Looking at the sim credits, a fair number of chemistry experts were a part of the team, so I suspect we made a deliberate choice to use `±n` instead of `n±`, likely to make the simulation more accessible to younger learners. Skimming through the design doc, I didn't see a documented reason, though.

I suspect a large number of users, especially those in universities or abroad, would prefer to use the standard IUPAC notation. This seems like a good candidate for a query parameter that corresponds to a radio button group in the Simulation tab of the Preferences. Perhaps something like this:
 <img width="306" alt="image" src="https://user-images.githubusercontent.com/8419308/196291635-d08afeaf-69bc-45c9-9888-c21d43dd9cea.png">

I don't have a great idea for the query parameter name, but perhaps `chargeNotation=signFirst` and `chargeNotation=signLast` could work.

I'd be curious to hear input from @emily-phet or @BLFiedler since they have more expertise in this area.

**Comment by DianaTavares** [comment]
I really like @arouinfar idea! It supports early learners and the math application of this sim. We can have the default the ±n, and advanced teachers to change it to the standard notation.

**Comment by BLFiedler** [comment]
It does strike me as a good candidate for the preferences menu, as more folks will see it than only an advertised query parameter in say the teacher tips. With respect to how the pref menu and query parameter interact, you may have to finesse.

For example, re: how the query parameter and pref menu buttons might interact We're currently using a toggle in the Sim tab of the Pref menu for Quadrilateral which changes two parameters at once and are also (currently) query parameters. Toggling this ON in the pref menu will _override_ the "step size" query parameter and then revert to the query parameter otherwise when off. For the other parameter toggling it ON changes a scaling factor (for a tolerance), so the query parameter is carried through the calculation when toggling.

![image](https://user-images.githubusercontent.com/47331395/196984002-97ef8811-a6d3-48a4-a05c-6cfb44e55a43.png)

**Comment by arouinfar** [comment]
@jbphet I added this to the Issues of Choice project board. BAA contains an error in the charge notation that would be nice to address. I did a deep review of the sim to make sure we caught all the places where the charge notation appears.

Places to update charge notation:
- [ ] Teacher Tips
- [x] Symbol representation on Symbol screen: https://github.com/phetsims/build-an-atom/commit/83a5ce937294859efb5ab6ac3507643fdc2055ec
- [x] Symbol screen icons: I updated the assets, keeping the same filenames and dimensions as those currently checked in. (Note that the current assets use "element" in the filename instead of "symbol".)
- [ ] Check-in updated assets: [symbol-screen-updated-assets.zip](https://github.com/phetsims/build-an-atom/files/10845326/symbol-screen-updated-assets.zip) 
- Game Screen displays the net charge in a few places
  - Level 2 (no change necessary): There is a prompt that asks students to determine the net charge. The associated spinner has the sign before the number. I don't think we need to change the notation here because it feels more tied to the "Net Charge" representation on the Atom screen, which we decided to leave alone. 
  <img src="https://user-images.githubusercontent.com/8419308/221719559-9ff75db9-f964-44bb-b132-b0ddbfcc1536.png" width=300>

  - RewardNode (no change necessary): There are images of the symbol that rain down when the RewardNode is triggered. Luckily, the net charge is always zero.
  <img src="https://user-images.githubusercontent.com/8419308/221720255-5f159890-251b-428e-9a81-d7ab185b53d8.png" width=300>

  - [ ] Levels 3 & 4 both contain symbol notation that needs updating. Here are a few examples:
  <img src="https://user-images.githubusercontent.com/8419308/221719024-13e5cff3-e5ac-4727-878b-21c5e75b0a8d.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/221719027-1a0f380c-b89d-4c99-9b34-1673840f15b4.png" width=300>

**Comment by jbphet** [comment]
@arouinfar - This is fixed on master and in the 1.6 branch, which is the branch from which the current published version is derived.  Can you please look it over (on master) and make sure you're good with the behavior?  I ended up having to use some different minus signs for when the sign is before the number (unary minus) and after (normal minus) to keep things consistent with plus signs and looking reasonably good.  I'd like you to check it out before we move to the next phase.  If you're good with it, I'll create an RC and have you check that over in greater detail.

**Comment by jbphet** [comment]
Thanks @arouinfar.  I've published an RC for this, please check it out at https://phet-dev.colorado.edu/html/build-an-atom/1.6.25-rc.1/build-an-atom_en.html.  I talked with QA, and they have a fair amount on their plate at the moment, so I'm okay with having you and me verify this if you are.  Please test drive it, let me know if you see any issues and, if not, I'll check it over one more time and proceed with publication if we don't find any problems.

**Comment by jbphet** [comment]
I just published version 1.6.25 with the change discussed above.

@oliver-phet - I'm assigning this back to you in case you want to notify the folks who requested this change that it has been implemented.  After that, feel free to close.

**Comment by oliver-phet** [comment]
All 3 users emailed with a link to the new version!

**Comment by arouinfar** [comment]
Thanks @oliver-phet @jbphet! I've uploaded the updated Teacher Tips to the website.
