### ISSUE TITLE
Impossible set state in game screen

### ISSUE THREAD

**Issue by zepumph** [phetsims/build-an-atom#198]
There are many errors on the Build An Atom game screen as they pertain to state. Many of them are disposal issues with tandem, but some have to do with setting the state.

@samreid and @zepumph decided that we don't think it is the best use of our time to try to fix all of the broken set state problems, since they are downstream of an "instrument everything" philosophy that we are no longer looking to follow.

Instead we should just remove BAA game screen from being tested with the state wrapper.

**Comment by zepumph** [comment]
The above commits are how far @samreid and @zepumph got before we decided to just turn off testing the game screen for the state wrapper. This should be removed when we revisit this sim with thoughtful API design. That commit to come.

**Comment by zepumph** [comment]
Tagging @jbphet so that he is aware that we gave up on trying to get the state wrapper to run successfully in the wrapper fuzzing. I also want to note that this has never worked. I remember spending many hours adding disposal through challenges, but never made it all the way through. 

We will revisit what specifically needs to be in the state as part of the redesign. 
For not I would like to assign the above commits over to @jbphet to review (only the BAA ones and/or whatever makes sense to you). @samreid and @zepumph have already checked off on them. Feel free to close from here if all sounds good.

**Comment by jbphet** [comment]
Thanks for the update, and I'm aware that the state wrapper isn't working for the game.  I briefly looked over the commits above.  Several of them are for the phet-io wrappers, and some for qunit testing, which I don't know much about.  I assume they're fine since BAA isn't failing any tests.  Closing, and I guess we'll get back to figuring out how to handle games in phet-io sometime in the future.
