### ISSUE TITLE
Sluggish Particle Motion on iOS7 - iPad 3

### ISSUE THREAD

**Issue by emily-phet** [phetsims/build-an-atom#38]
When dragging particles into the atom model, there is a pause before the sim seems to 'register' where the particle belongs and to update the readouts. Essentially, in the time it takes the sim to register the addition of a new proton (for example) in the nucleus, I can move my hand all the way out of the way and be trying to grab another.

Upon dragging particles out, it "feels" like I drag my finger across the nucleus and down, and the particle appears under my finger half way to the bucket. This does not occur on dragging particles in, i can see the particle the whole time when i'm dragging in. 

I'm assuming these are related, hence the one issue. 

These aren't deal breakers, but it's definitely not ideal (particularly the slow registering of the addition of a particle). 

Here's the sim info:
Name: Build an Atom
URL: http://www.colorado.edu/physics/phet/dev/html/build-an-atom/1.1.0-rc/2/build-an-atom_en.html
Version: 1.1.0-rc.1
Features missing: fullscreen
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (iPad; CPU OS 7_0_2 lik Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A501 Safari/9537.53
Language: en-us
Window: 1024x672
Pixel Ratio: 2/1

**Comment by jbphet** [comment]
Assigning to @phet-steele to qualify performance on most recent iOS+iPad versions and log an opinion as to whether performance is acceptable.

**Comment by phet-steele** [comment]
Tested 1.2.0-dev.2:

iPad Air 2 iOS 9.2: fantastic performance as usual.

iPad 2 iOS 9.3 Beta 3: dragging is slightly sluggish, could be improved but isn't too bad. Pressing "Next" to go to the next challenge in the first game (with the periodic tables) maybe has a ~0.5 second delay.

iPad 3 iOS 9.2: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1: :-1:

**Comment by jbphet** [comment]
I just tested on an iPad 3 running iOS 9.3 (our iPad 3 - "Disessa" - has been upgraded since this was last tested).  The performance isn't great, but the sim is definitely usable.  It's also no worse than the currently published version.  Regardless, I'll try a few basic things to try to improve performance.

**Comment by jbphet** [comment]
To try to quantify the performance in a repeatable way, I ran the sim on the test iPads using the ```profiler``` query parameter, went to the first screen, picked up a proton with my finger, and moved it clockwise around the outer electron shell at one revolution per second.  I used a metronome to time the motion.  On "Disessa", an iPad 3 running iOS 9.3, the performance went down to about 9 fps.  On "Witten", an iPad 2 running iOS 9.3, it went to about 10 fps.  I worked with @jonathanolson to come up with some potential optimizations, such as changing where the layer splits were in the scene graph.  The only ones that seemed to help was making a couple of things unpickable so that the weren't being hit tested (see the commits for details).  This got the frame rate up to 11 fps on Disessa and 12 fps on Witten.  Not a huge gain, but better than nothing.

**Comment by jbphet** [comment]
In my opinion, the sim is quite usable on the iPads I tested it on, which are at this point some older devices.  I think this is about as good as it's going to get without a major time investment.  I'm going to unassign this issue and will have it tested during upcoming RC testing to determine whether it's acceptable.

**Comment by jbphet** [comment]
I reviewed the performance of this with @ariel-phet yesterday, and we agreed that the performance isn't great on iPad 3, but it's reasonably acceptable given the relatively low usage of this device.  Things are better on iPad 2 and way better on iPad 4, so this issue is not a roadblock to redeployment.

**Comment by jbphet** [comment]
Given that we've decided to move forward with the 1.2 release, and that the performance is acceptable, I'm going to close this issue.
